_target_: datasets.cifar10.CIFAR10LDM
data_path: ${datadir}
batch_size: 256
num_workers: 4
num_classes: 10
valid_fraction: 0.05
random_seed: 42
amplification: 1
ignore_first_timesteps: 0
input_size: 3
