_target_: datasets.csmnist.CSMNISTLDM
data_path: ${datadir}
dt: 1000
batch_size: 512
num_workers: 4
num_classes: 10
valid_fraction: 0.05
random_seed: 42
window_size: 1000
amplification: 1
ignore_first_timesteps: 700
