_target_: datasets.smnist.SMNISTLDM
data_path: ${datadir}
input_size: 33
dt: 1000
batch_size: 512
num_workers: 4
num_classes: 10
valid_fraction: 0.05
random_seed: 42
window_size: 1000
ignore_first_timesteps: 700
